### ISSUE TITLE
[MRESOLVER-21] Maven Resolver trying to resolve optional dependencies

### ISSUE THREAD

**Issue by olamy** [olamy/maven-resolver#21]
**[Cedric Beust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cbeust)** opened **[MRESOLVER-21](https://issues.apache.org/jira/browse/MRESOLVER-21?redirect=false)** and commented

I modified the `ResolveTransitiveDependencies.java` example in two ways:

- Modified the id to `"org.springframework:spring-context-support:2.5.6.SEC03"`
- Replaced the filter with one that excludes optional dependencies

I'm including the full code below.

Despite that, `system.resolveDependencies()` fails with a `DependencyResolutionException when trying to resolve a bunch of optional dependencies, sugh as `jasperreports`.

Head of the stack trace:

```
org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.springframework:spring-context-support:jar:2.5.6.SEC03 -> jasperreports:jasperreports:jar:2.0.5 -> commons-logging:commons-logging:jar:99.0-does-not-exist
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:380)
	at org.apache.maven.resolver.examples.ResolveTransitiveDependencies.main(ResolveTransitiveDependencies.java:71)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.springframework:spring-context-support:jar:2.5.6.SEC03 -> jasperreports:jasperreports:jar:2.0.5 -> commons-logging:commons-logging:jar:99.0-does-not-exist
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	... 1 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for commons-logging:commons-logging:jar:99.0-does-not-exist
```

```java
    public static void main( String[] args )
        throws Exception
    {
        System.out.println( "------------------------------------------------------------" );
        System.out.println( ResolveTransitiveDependencies.class.getSimpleName() );

        RepositorySystem system = Booter.newRepositorySystem();

        RepositorySystemSession session = Booter.newRepositorySystemSession( system );

        Artifact artifact = new DefaultArtifact( "org.springframework:spring-context-support:2.5.6.SEC03" );

        DependencyFilter classpathFlter = DependencyFilterUtils.classpathFilter( JavaScopes.COMPILE );
        DependencyFilter optionalFilter = new DependencyFilter() {
            @Override
            public boolean accept(DependencyNode dependencyNode, List<DependencyNode> list) {
                return ! dependencyNode.getDependency().getOptional();
            }
        };
        CollectRequest collectRequest = new CollectRequest();
        collectRequest.setRoot( new Dependency( artifact, JavaScopes.COMPILE ) );
        collectRequest.setRepositories( Booter.newRepositories( system, session ) );

        DependencyRequest dependencyRequest = new DependencyRequest( collectRequest, optionalFilter );

        try {
            List<ArtifactResult> artifactResults =
                    system.resolveDependencies(session, dependencyRequest).getArtifactResults();

            for (ArtifactResult artifactResult : artifactResults) {
                System.out.println(artifactResult.getArtifact() + " resolved to "
                        + artifactResult.getArtifact().getFile());
            }
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
```

---
No further details from [MRESOLVER-21](https://issues.apache.org/jira/browse/MRESOLVER-21?redirect=false)

**Comment by olamy** [comment]
**[Cedric Beust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cbeust)** commented

An update to this ticket: the error only happens if I add JCenter in the list of repos:

```
new RemoteRepository.Builder( "jcenter", "default", "https://jcenter.bintray.com" ).build()
```

If there's only Maven Central, the resolution succeeds.

**Comment by olamy** [comment]
**[Cedric Beust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cbeust)** commented

Digging into the rabbit hole further.

Here is the lovely dependency that JCenter has:

http://jcenter.bintray.com/commons-logging/commons-logging/99.0-does-not-exist/

The parent dependency is `jasperreports/jasperreports/2.0.5/jasperreports-2.0.5.pom` and it depends on `commons-logging` with:

```
<dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>[1.0,)</version>
        <scope>compile</scope>
</dependency>
```

It's a version range, so Maven Resolver takes the highest it can find on JCenter, which is... 99-doesnt-exist. And boom.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

How are we supposed to fixed this if the Jasper Reports POM is inprecise?

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction of a fix proposal.
