### ISSUE TITLE
[MRESOLVER-362] NoSuchFileException moving .tmp to .jar

### ISSUE THREAD

**Issue by olamy** [olamy/maven-resolver#59]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** opened **[MRESOLVER-362](https://issues.apache.org/jira/browse/MRESOLVER-362?redirect=false)** and commented

It looks like MRESOLVER-290 broke our metadata verification tests. We have a test that uses the resolver API to collect a bunch of dependencies, and checking the state is correct. Since the upgrade to 1.9 we get this

```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.boot:spring-boot-starter:jar:3.0.8-20230525.115211-13 from/to spring-snapshots (https://repo.spring.io/snapshot): /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar.4959477968260906889.tmp -> /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:448)
	... 45 more
Caused by: java.nio.file.NoSuchFileException: /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar.4959477968260906889.tmp -> /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.eclipse.aether.util.FileUtils$2.move(FileUtils.java:108)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:500)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
```

The test is here https://github.com/spring-io/start.spring.io/tree/main/start-site-verification/src/test/java/io/spring/start/site

---

**Affects:** 1.9.10

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll), can this reliably re reproduced?

**Comment by olamy** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Yes. I have a particular occurrence that fails every time, and on that same artifact above.

**Comment by olamy** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Was there some transport error involved here? Any peculiarity?

**Comment by olamy** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

I was able to build, but have various (not reported) test issues, but as I see, they stem from environment, like tests are picking up my maven env? (settings.xml)

Retrying by "resetting" env (I used mvn -s settings.xml but seems my home .m2/settings.xml did mixed in)

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I can reproduce it as well.

**Comment by olamy** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Created change proposal (but unsure about actual use case) https://github.com/snicoll-scratches/MRESOLVER-362/pull/1

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I am against being lenient with violators.

**Comment by olamy** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Thanks so much. This was indeed a problem on our end and there is more info in https://github.com/snicoll-scratches/MRESOLVER-362/pull/1
